language: node_js

notifications:
  email: false

node_js:
  - v8
  - v7
  - v6

branches:
  only:
    - master
    - /^greenkeeper/.*$/

addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
